#ifndef STDAFX_H
#define STDAFX_H

#include <cstdlib>
#include <QApplication>
#include <QBitmap>
#include <QCloseEvent>
#include <QDateTime>
#include <QDialog>
#include <QEventLoop>
#include <QKeyEvent>
#include <QListWidgetItem>
#include <QMap>
#include <QMainWindow>
#include <QMessageBox>
#include <QMouseEvent>
#include <QMenu>
#include <QPainter>
#include <QPainterPath>
#include <QPaintEvent>
#include <QRect>
#include <QString>
#include <QSystemTrayIcon>
#include <QTextCodec>
#include <QTimer>
#include <QThread>
#include <QtNetwork>
#include <string>
#include <vector>

#endif //STDAFX_H
