#include <cstdlib>
#include <QApplication>
#include <QBitmap>
#include <QEventLoop>
#include <QKeyEvent>
#include <QMainWindow>
#include <QMessageBox>
#include <QMouseEvent>
#include <QPainter>
#include <QPainterPath>
#include <QPaintEvent>
#include <QRect>
#include <QTextCodec>
#include <QTimer>
#include <QThread>
