#ifndef STDAFX_H
#define STDAFX_H

#include <QApplication>
#include <QCloseEvent>
#include <QDateTime>
#include <QEventLoop>
#include <QFileDialog>
#include <QGroupBox>
#include <QImage>
#include <QImageReader>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QJsonValue>
#include <QLinearGradient>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QListWidgetItem>
#include <QMap>
#include <QMainWindow>
#include <QMessageBox>
#include <QMouseEvent>
#include <QMenu>
#include <QPainter>
#include <QPainterPath>
#include <QPaintEvent>
#include <QPoint>
#include <QPushButton>
#include <QRadioButton>
#include <QRect>
#include <QString>
#include <QtSql>
#include <QSystemTrayIcon>
#include <QTextCodec>
#include <QTextEdit>
#include <QTimer>
#include <QThread>
#include <QtNetwork>
#include <QVector>
#include <QWidget>

#endif //STDAFX_H
